# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stock_pb2 as stock__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StockearteServiceStub(object):
    """Servicios
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearUsuario = channel.unary_unary(
                '/stock.StockearteService/CrearUsuario',
                request_serializer=stock__pb2.Usuario.SerializeToString,
                response_deserializer=stock__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.AutenticarUsuario = channel.unary_unary(
                '/stock.StockearteService/AutenticarUsuario',
                request_serializer=stock__pb2.Usuario.SerializeToString,
                response_deserializer=stock__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.CrearTienda = channel.unary_unary(
                '/stock.StockearteService/CrearTienda',
                request_serializer=stock__pb2.Tienda.SerializeToString,
                response_deserializer=stock__pb2.TiendaResponse.FromString,
                _registered_method=True)
        self.ModificarTienda = channel.unary_unary(
                '/stock.StockearteService/ModificarTienda',
                request_serializer=stock__pb2.Tienda.SerializeToString,
                response_deserializer=stock__pb2.TiendaResponse.FromString,
                _registered_method=True)
        self.AlternarHabilitadaTienda = channel.unary_unary(
                '/stock.StockearteService/AlternarHabilitadaTienda',
                request_serializer=stock__pb2.Tienda.SerializeToString,
                response_deserializer=stock__pb2.TiendaResponse.FromString,
                _registered_method=True)
        self.CrearProducto = channel.unary_unary(
                '/stock.StockearteService/CrearProducto',
                request_serializer=stock__pb2.Producto.SerializeToString,
                response_deserializer=stock__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.ModificarProducto = channel.unary_unary(
                '/stock.StockearteService/ModificarProducto',
                request_serializer=stock__pb2.Producto.SerializeToString,
                response_deserializer=stock__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.EliminarProducto = channel.unary_unary(
                '/stock.StockearteService/EliminarProducto',
                request_serializer=stock__pb2.Producto.SerializeToString,
                response_deserializer=stock__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.BuscarUsuarios = channel.unary_unary(
                '/stock.StockearteService/BuscarUsuarios',
                request_serializer=stock__pb2.BuscarUsuariosRequest.SerializeToString,
                response_deserializer=stock__pb2.BuscarUsuariosResponse.FromString,
                _registered_method=True)
        self.BuscarTiendas = channel.unary_unary(
                '/stock.StockearteService/BuscarTiendas',
                request_serializer=stock__pb2.BuscarTiendasRequest.SerializeToString,
                response_deserializer=stock__pb2.BuscarTiendasResponse.FromString,
                _registered_method=True)
        self.BuscarProductos = channel.unary_unary(
                '/stock.StockearteService/BuscarProductos',
                request_serializer=stock__pb2.BuscarProductosRequest.SerializeToString,
                response_deserializer=stock__pb2.BuscarProductosResponse.FromString,
                _registered_method=True)


class StockearteServiceServicer(object):
    """Servicios
    """

    def CrearUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutenticarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlternarHabilitadaTienda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarProducto(self, request, context):
        """Considerar solo recibir el código
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarTiendas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockearteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearUsuario,
                    request_deserializer=stock__pb2.Usuario.FromString,
                    response_serializer=stock__pb2.UsuarioResponse.SerializeToString,
            ),
            'AutenticarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AutenticarUsuario,
                    request_deserializer=stock__pb2.Usuario.FromString,
                    response_serializer=stock__pb2.UsuarioResponse.SerializeToString,
            ),
            'CrearTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearTienda,
                    request_deserializer=stock__pb2.Tienda.FromString,
                    response_serializer=stock__pb2.TiendaResponse.SerializeToString,
            ),
            'ModificarTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarTienda,
                    request_deserializer=stock__pb2.Tienda.FromString,
                    response_serializer=stock__pb2.TiendaResponse.SerializeToString,
            ),
            'AlternarHabilitadaTienda': grpc.unary_unary_rpc_method_handler(
                    servicer.AlternarHabilitadaTienda,
                    request_deserializer=stock__pb2.Tienda.FromString,
                    response_serializer=stock__pb2.TiendaResponse.SerializeToString,
            ),
            'CrearProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearProducto,
                    request_deserializer=stock__pb2.Producto.FromString,
                    response_serializer=stock__pb2.ProductoResponse.SerializeToString,
            ),
            'ModificarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarProducto,
                    request_deserializer=stock__pb2.Producto.FromString,
                    response_serializer=stock__pb2.ProductoResponse.SerializeToString,
            ),
            'EliminarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarProducto,
                    request_deserializer=stock__pb2.Producto.FromString,
                    response_serializer=stock__pb2.ProductoResponse.SerializeToString,
            ),
            'BuscarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarUsuarios,
                    request_deserializer=stock__pb2.BuscarUsuariosRequest.FromString,
                    response_serializer=stock__pb2.BuscarUsuariosResponse.SerializeToString,
            ),
            'BuscarTiendas': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarTiendas,
                    request_deserializer=stock__pb2.BuscarTiendasRequest.FromString,
                    response_serializer=stock__pb2.BuscarTiendasResponse.SerializeToString,
            ),
            'BuscarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarProductos,
                    request_deserializer=stock__pb2.BuscarProductosRequest.FromString,
                    response_serializer=stock__pb2.BuscarProductosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stock.StockearteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stock.StockearteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StockearteService(object):
    """Servicios
    """

    @staticmethod
    def CrearUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/CrearUsuario',
            stock__pb2.Usuario.SerializeToString,
            stock__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutenticarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/AutenticarUsuario',
            stock__pb2.Usuario.SerializeToString,
            stock__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/CrearTienda',
            stock__pb2.Tienda.SerializeToString,
            stock__pb2.TiendaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/ModificarTienda',
            stock__pb2.Tienda.SerializeToString,
            stock__pb2.TiendaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlternarHabilitadaTienda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/AlternarHabilitadaTienda',
            stock__pb2.Tienda.SerializeToString,
            stock__pb2.TiendaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/CrearProducto',
            stock__pb2.Producto.SerializeToString,
            stock__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/ModificarProducto',
            stock__pb2.Producto.SerializeToString,
            stock__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/EliminarProducto',
            stock__pb2.Producto.SerializeToString,
            stock__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/BuscarUsuarios',
            stock__pb2.BuscarUsuariosRequest.SerializeToString,
            stock__pb2.BuscarUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarTiendas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/BuscarTiendas',
            stock__pb2.BuscarTiendasRequest.SerializeToString,
            stock__pb2.BuscarTiendasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockearteService/BuscarProductos',
            stock__pb2.BuscarProductosRequest.SerializeToString,
            stock__pb2.BuscarProductosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
