# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usuario_pb2 as usuario__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearUsuario = channel.unary_unary(
                '/usuario.UsuarioService/CrearUsuario',
                request_serializer=usuario__pb2.CrearUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.ModificarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/ModificarUsuario',
                request_serializer=usuario__pb2.ModificarUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.BorrarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/BorrarUsuario',
                request_serializer=usuario__pb2.BorrarUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.BuscarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/BuscarUsuario',
                request_serializer=usuario__pb2.BuscarUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.EnlistarUsuarios = channel.unary_unary(
                '/usuario.UsuarioService/EnlistarUsuarios',
                request_serializer=usuario__pb2.EnlistarUsuariosRequest.SerializeToString,
                response_deserializer=usuario__pb2.UsuariosResponse.FromString,
                _registered_method=True)
        self.AutenticarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/AutenticarUsuario',
                request_serializer=usuario__pb2.AutenticarUsuarioRequest.SerializeToString,
                response_deserializer=usuario__pb2.AutenticarUsuarioResponse.FromString,
                _registered_method=True)


class UsuarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearUsuario(self, request, context):
        """CRUD Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModificarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnlistarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutenticarUsuario(self, request, context):
        """Authentication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearUsuario,
                    request_deserializer=usuario__pb2.CrearUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.UsuarioResponse.SerializeToString,
            ),
            'ModificarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ModificarUsuario,
                    request_deserializer=usuario__pb2.ModificarUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.UsuarioResponse.SerializeToString,
            ),
            'BorrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrarUsuario,
                    request_deserializer=usuario__pb2.BorrarUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.UsuarioResponse.SerializeToString,
            ),
            'BuscarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarUsuario,
                    request_deserializer=usuario__pb2.BuscarUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.UsuarioResponse.SerializeToString,
            ),
            'EnlistarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.EnlistarUsuarios,
                    request_deserializer=usuario__pb2.EnlistarUsuariosRequest.FromString,
                    response_serializer=usuario__pb2.UsuariosResponse.SerializeToString,
            ),
            'AutenticarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AutenticarUsuario,
                    request_deserializer=usuario__pb2.AutenticarUsuarioRequest.FromString,
                    response_serializer=usuario__pb2.AutenticarUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuario.UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuario.UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/CrearUsuario',
            usuario__pb2.CrearUsuarioRequest.SerializeToString,
            usuario__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModificarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/ModificarUsuario',
            usuario__pb2.ModificarUsuarioRequest.SerializeToString,
            usuario__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/BorrarUsuario',
            usuario__pb2.BorrarUsuarioRequest.SerializeToString,
            usuario__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/BuscarUsuario',
            usuario__pb2.BuscarUsuarioRequest.SerializeToString,
            usuario__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnlistarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/EnlistarUsuarios',
            usuario__pb2.EnlistarUsuariosRequest.SerializeToString,
            usuario__pb2.UsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutenticarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/AutenticarUsuario',
            usuario__pb2.AutenticarUsuarioRequest.SerializeToString,
            usuario__pb2.AutenticarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
